# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# postgres or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:latest
    restart: always
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
volumes:
  postgres:
  minio:
