import a from './a.svelte';
import blockquote from './blockquote.svelte';
import code from './code.svelte';
import codeblock from './codeblock.svelte';
import h2 from './h2.svelte';
import h3 from './h3.svelte';
import h4 from './h4.svelte';
import h5 from './h5.svelte';
import img from './img.svelte';
import ol from './ol.svelte';
import p from './p.svelte';
import pre from './pre.svelte';
import ul from './ul.svelte';
export { a, blockquote, code, codeblock, h2, h3, h4, h5, img, ol, p, pre, ul };
